### ISSUE TITLE
publish docs hexdocs.pm

### ISSUE THREAD

**Issue by igalic** [meyercm/base_model#1]
The docs are sort of published to hexdocs: https://hexdocs.pm/base_model/

but it's empty!

I don't quite understand why… given that there's `@docs` everywhere…

**Comment by meyercm** [comment]
Very strange!  I'm not actually sure what's going on there.  I've been planning to push a new version, so perhaps that will force a reset on the docs. In the meantime, refer to the README, the example repo, and the tests to see how it should be used; also feel free to comment if you are confused about something.

**Comment by meyercm** [comment]
I've just pushed `0.2.1`, which adds documentation to `BaseModel` directly, instead of just to the generated code- this is why the HexDocs were blank before.  Let me know if you see any deficiencies in the documentation.  Thanks again for reporting the issue!
