### ISSUE TITLE
Compile warning when implement `create_changeset`: got "@impl BaseModel" for function create_changeset/1 but no behaviour was declared

### ISSUE THREAD

**Issue by ChrisZou** [meyercm/base_model#2]
Hi @meyercm, thank you so much for making this lib. It's been a great help for me. There is a tiny issue though, when I define a `create_changeset` in my schema, there is this compiling error said:
`got "@impl BaseModel" for function create_changeset/1 but no behaviour was declared`.
The code of the schema looked like this:

```
defmodule AnnualPlan do
  use Ecto.Schema
  use BaseModel, repo: MyApp.Repo

  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id
  schema "annual_plans" do
    field(:body, :string)
    field(:year, :string)
    belongs_to(:user, MyApp.Accounts.User, type: :integer)

    timestamps()
  end

  @impl BaseModel
  def create_changeset(params) do
    %__MODULE__{}
    |> cast(params, [:year, :body, :user_id])
    |> validate_required([:year, :body, :user_id])
  end
end
```

Although the `create_changeset` function still works, it would be great if there is no compile warning. Was I missing something?

**Comment by meyercm** [comment]
Can you check that you are locked to the `0.2.1` version of `base_model`, by running `mix deps | grep base_model` at the shell?

**Comment by ChrisZou** [comment]
@meyercm I used the 0.2 version, I'll update to 0.2.1 and see if it still exist. Thank you!

**Comment by ChrisZou** [comment]
Hi @meyercm , I upgraded to version 0.2.1 and the compile warning is gone. Thank you and sorry for the delay.

**Comment by meyercm** [comment]
No worries.  I'm glad that you were able to fix it easily.
